name: Run Unit Tests

on:
  push:
    branches:
      - '**' # Run on every branch push
  pull_request:
    branches:
      - '**' # Optional: run on every PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
